// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function HistoryRow(props) {
  var amount = props.amount;
  var displayAmount = amount.includes("-") ? "-$" + amount : "+$" + amount;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: props.remarks,
                      className: "text-sm font-normal"
                    }),
                JsxRuntime.jsx("div", {
                      children: displayAmount,
                      className: "text-sm font-normal"
                    }),
                amount.includes("-") ? JsxRuntime.jsx("span", {
                        className: "absolute w-[4px] h-full right-0 top-0 bg-red-700"
                      }) : JsxRuntime.jsx("span", {
                        className: "absolute w-[4px] h-full right-0 top-0 bg-green-400"
                      })
              ],
              className: "bg-white border border-gray-200 px-2 py-1 shadow-sm relative flex flex-row items-center justify-between"
            });
}

var make = HistoryRow;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
