// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function HistoryRow(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: "Cash",
                      className: "text-sm font-normal"
                    }),
                JsxRuntime.jsx("div", {
                      children: "+$400.0",
                      className: "text-sm font-normal"
                    }),
                JsxRuntime.jsx("span", {
                      className: "absolute w-[4px] h-full right-0 top-0 bg-red-700"
                    })
              ],
              className: "bg-white border border-gray-200 px-2 py-1 shadow-sm relative flex flex-row items-center justify-between"
            });
}

var make = HistoryRow;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
