// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function TextInput(props) {
  var description = props.description;
  var middleGapClass = description !== undefined ? "" : "pb-1";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("p", {
                      children: props.title,
                      className: "" + middleGapClass + " text-sm font-medium"
                    }),
                description !== undefined ? JsxRuntime.jsx("p", {
                        children: description,
                        className: "text-xs pb-2 font-medium"
                      }) : null,
                JsxRuntime.jsx("input", {
                      className: "text-sm font-medium focus:outline-none",
                      type: props.type_,
                      onChange: props.onChange
                    })
              ],
              className: "flex flex-col"
            });
}

var make = TextInput;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
