// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var appInitialState_transactionHistoryList = [];

function appInitialState_addTransaction(remarks, amount) {
  
}

var appInitialState = {
  balanceAmount: 0.0,
  incomeAmount: 0.0,
  expenseAmount: 0.0,
  transactionHistoryList: appInitialState_transactionHistoryList,
  addTransaction: appInitialState_addTransaction
};

var context = React.createContext(appInitialState);

function useAppContext(param) {
  return React.useContext(context);
}

export {
  appInitialState ,
  context ,
  useAppContext ,
}
/* context Not a pure module */
