// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppContext from "./AppContext.bs.mjs";

var make = AppContext.context.Provider;

var makeProps = [
  "value",
  "children"
];

export {
  make ,
  makeProps ,
}
/* make Not a pure module */
