// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HistoryBlock from "./HistoryBlock.bs.mjs";
import * as BalanceAmount from "./BalanceAmount.bs.mjs";
import * as IncomeExpenseBox from "./IncomeExpenseBox.bs.mjs";
import * as TransactionBlock from "./TransactionBlock.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ExpenseTrackerHeader from "./ExpenseTrackerHeader.bs.mjs";

function App(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(ExpenseTrackerHeader.make, {}),
                JsxRuntime.jsx(BalanceAmount.make, {}),
                JsxRuntime.jsx(IncomeExpenseBox.make, {}),
                JsxRuntime.jsx(HistoryBlock.make, {}),
                JsxRuntime.jsx(TransactionBlock.make, {})
              ],
              className: "app-background h-screen w-screen p-4 overflow-y-auto"
            });
}

var make = App;

export {
  make ,
}
/* HistoryBlock Not a pure module */
