// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function BalanceAmount(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: "Your Balance",
                      className: "mt-1 uppercase text-sm"
                    }),
                JsxRuntime.jsx("div", {
                      children: "$0.00",
                      className: "text-2xl xl:text-3xl text-black font-bold"
                    })
              ],
              className: "my-5"
            });
}

var make = BalanceAmount;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
