// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppContext from "./Context/AppContext.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function BalanceAmount(props) {
  var match = AppContext.useAppContext(undefined);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: "Your Balance",
                      className: "mt-1 uppercase text-sm"
                    }),
                JsxRuntime.jsx("div", {
                      children: match.balanceAmount,
                      className: "text-2xl xl:text-3xl text-black font-bold"
                    })
              ],
              className: "my-5"
            });
}

var make = BalanceAmount;

export {
  make ,
}
/* AppContext Not a pure module */
