// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function ExpenseTrackerHeader(props) {
  return JsxRuntime.jsx("h1", {
              children: "Expense Tracker",
              className: "text-xl xl:text-2xl text-black font-medium"
            });
}

var make = ExpenseTrackerHeader;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
