// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Headings(props) {
  return JsxRuntime.jsx("div", {
              children: props.title,
              className: "font-medium pb-1 border-b border-gray-300"
            });
}

var make = Headings;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
