// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Headings from "./Headings.bs.mjs";
import * as HistoryRow from "./HistoryBlock/HistoryRow.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function HistoryBlock(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Headings.make, {
                      title: "History"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(HistoryRow.make, {}),
                        JsxRuntime.jsx(HistoryRow.make, {}),
                        JsxRuntime.jsx(HistoryRow.make, {}),
                        JsxRuntime.jsx(HistoryRow.make, {}),
                        JsxRuntime.jsx(HistoryRow.make, {})
                      ],
                      className: "mt-2 space-y-2"
                    })
              ],
              className: "mt-5"
            });
}

var make = HistoryBlock;

export {
  make ,
}
/* Headings Not a pure module */
