// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function IncomeExpenseBox(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("p", {
                                    children: "INCOME"
                                  }),
                              JsxRuntime.jsx("p", {
                                    children: "0.00",
                                    className: "text-green-400"
                                  })
                            ],
                            className: "px-10 font-medium text-sm flex flex-col items-center border-r broder-gray-300"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("p", {
                                    children: "EXPENSE"
                                  }),
                              JsxRuntime.jsx("p", {
                                    children: "0.00",
                                    className: "text-red-700"
                                  })
                            ],
                            className: "px-10 font-medium text-sm flex flex-col items-center "
                          })
                    ],
                    className: "flex flex-row items-center justify-center"
                  }),
              className: "bg-white border border-gray-200 shadow-sm py-4"
            });
}

var make = IncomeExpenseBox;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
