// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Headings from "./Headings.bs.mjs";
import * as TextInput from "./TransactionBlock/TextInput.bs.mjs";
import * as AppContext from "./Context/AppContext.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function TransactionBlock(props) {
  var match = AppContext.useAppContext(undefined);
  var addTransaction = match.addTransaction;
  var match$1 = React.useState(function () {
        return "";
      });
  var setRemarkText = match$1[1];
  var remarkText = match$1[0];
  var match$2 = React.useState(function () {
        return "0";
      });
  var setAmount = match$2[1];
  var amount = match$2[0];
  var handleChangeAmount = function (e) {
    var newAmount = e.target.value;
    Curry._1(setAmount, (function (param) {
            return newAmount;
          }));
  };
  var handleRemarkChange = function (e) {
    Curry._1(setRemarkText, e.target.value);
  };
  var handleAddTransaction = function (e) {
    Curry._2(addTransaction, remarkText, amount);
    Curry._1(setRemarkText, (function (param) {
            return "";
          }));
    Curry._1(setAmount, (function (param) {
            return "0";
          }));
    e.preventDefault();
  };
  var isButtonDisabled = remarkText === "" || amount === "0" ? true : false;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Headings.make, {
                      title: "Add new transaction"
                    }),
                JsxRuntime.jsx(TextInput.make, {
                      type_: "text",
                      onChange: handleRemarkChange,
                      title: "Text",
                      value: remarkText
                    }),
                JsxRuntime.jsx(TextInput.make, {
                      type_: "number",
                      onChange: handleChangeAmount,
                      title: "Amount",
                      value: amount,
                      description: "(negative - expense, positive - income)"
                    }),
                JsxRuntime.jsx("button", {
                      children: "Add Transaction",
                      className: "bg-indigo-600 text-white w-full py-2 disabled:bg-indigo-300",
                      disabled: isButtonDisabled,
                      onClick: handleAddTransaction
                    })
              ],
              className: "mt-5 space-y-3"
            });
}

var make = TransactionBlock;

export {
  make ,
}
/* react Not a pure module */
