// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Headings from "./Headings.bs.mjs";
import * as TextInput from "./TransactionBlock/TextInput.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function TransactionBlock(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Headings.make, {
                      title: "Add new transaction"
                    }),
                JsxRuntime.jsx(TextInput.make, {
                      type_: "text",
                      onChange: (function (param) {
                          
                        }),
                      title: "Text"
                    }),
                JsxRuntime.jsx(TextInput.make, {
                      type_: "number",
                      onChange: (function (param) {
                          
                        }),
                      title: "Amount",
                      description: "(negative - expense, positive - income)"
                    }),
                JsxRuntime.jsx("button", {
                      children: "Add Transaction",
                      className: "bg-indigo-600 text-white w-full py-2 disabled:bg-indigo-300",
                      disabled: true
                    })
              ],
              className: "mt-5 space-y-3"
            });
}

var make = TransactionBlock;

export {
  make ,
}
/* Headings Not a pure module */
